server:
  port: 7077
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5055/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  application:
    name: limesi-gateway