server:
  port: 8088
spring:
  security:
    user:
      name: root
      password: 123456
  application:
    name: limesi-auth
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/chuak?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT
    username: root
    password: Li049675
    tomcat:
      #初始大小
      initial-size: 3
      #链接超时时间
      max-wait: 60000
      validation-query: select 1
      #最小空闲连接数
      min-idle: 3
      #间隔多少时间检测
      time-between-eviction-runs-millis: 60000
      #最小生存时间
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
