server:
  port: 6066
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/limesi/spring-cloud-configuration.git
          search-paths: test/
          username: limesi@163.com
          password: Li049675
          default-label: master