server:
  port: 6066
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/limesi/spring-cloud-configuration.git
          search-paths: test/
          username: limesi@163.com
          password: Li049675
          default-label: master
        encrypt:
          enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5055/eureka/